export const LOAD_STORAGE_RECORDS_SUCCESS = 'LOAD_STORAGE_RECORDS_SUCCESS'
export const LOAD_SELECTED_STORAGE_RECORD_SUCCESS = 'LOAD_SELECTED_STORAGE_RECORD_SUCCESS'
export const DETELE_STORAGE_RECORDS_SUCCESS = 'DETELE_STORAGE_RECORDS_SUCCESS'
export const LOAD_RECORDS_FAILED = 'LOAD_RECORDS_FAILED'